baseURL = "https://isabella-l.github.io"
languageCode = "en-us"
theme = "glim-midnight"
title = 'Isabella Lu'

[params]
    title = "Hire Me As"
    phrases = ["Robotics Engineer", "Embedded Developer", "Computer Vision Researcher", "Web Programmer", "A Fun Person"]
    links = [   
    {name = "3AM Robotics Research", url = "https://bumblebee.sg/competitions/robosub/2023/"},    
    {name = "9AM - 5PM Internship", url = "https://aircraft.airbus.com/en/services/enhance/skywise"},
    {name = "LinkedIn", url = "https://www.linkedin.com/in/isabella-lusicheng/"},      
    {name = "Github", url = "https://github.com/Isabella-L"}, 
    {name = "Email", url = "mailto:lusicheng@u.nus.edu"},
    ] 
    background = "bg.mp4"